source "https://rubygems.org"

gem "github-pages", "~> 228"
gem "webrick", "~> 1.8"
gem "faraday-retry"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-github-metadata"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
end

gem 'csv'
gem 'base64'
